tfl_accidents_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
    cloud:
      type: postgres
      host: "{{ env_var('CLOUD_DB_HOST') }}"
      user: "{{ env_var('CLOUD_DB_USER') }}"
      password: "{{ env_var('CLOUD_DB_PASSWORD') }}"
      port: "{{ env_var('CLOUD_DB_PORT') | int }}"
      dbname: "{{ env_var('CLOUD_DB_NAME') }}"
      schema: public